apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cilium-egress-ha-operator.serviceAccountName" . }}
  labels:
    {{- include "cilium-egress-ha-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}