name: Lint Charts

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/lint.yml"
      - "charts/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/lint.yml"
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2
        with:
          command: lint
          config: .github/ct.yaml
